steps:
  # Build backend Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "backend/dev.Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA"
      - "./backend"

  # Push image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA"

  # Deploy the new image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--quiet"

substitutions:
  _REGION: "australia-southeast1"
  _REPOSITORY: "YOUR_ARTIFACT_REGISTRY_REPOSITORY"
  _IMAGE: "backend"
  _SERVICE: "YOUR_CLOUD_RUN_SERVICE"