services: # docker compose expects
  backend:
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    ports: 
      - 8080:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 #--reload
    environment:
      - PORT=8000
      - MY_PROJECT=Docker Deployment
    env_file:
      - .env.sample
    # volumes ignore dockerignore commands
    volumes: 
    - ./backend/src:/app
    depends_on:
      db_service:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/dev.Dockerfile
        # - action: sync
        #   path: ./backend/src
        #   target: /app
        - action: sync+restart
          path: ./backend/src
          target: /app
  # DB_URL = postgresql+psycopg://username:password@dbhost:dbport/dbname
  db_service:
    image: postgres:17.11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=mydb
    # env_file:
      # - .env.sample-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - dc_managed_db_volume:/var/lib/postgresql/data
  static_html: # custom key name
    # image: python:3.14
    build:
      context: ./static_html
      dockerfile: static.Dockerfile
    ports:
    # local machine port: container port
      - 8000:8000
      - 3000:8000
    command: python -m http.server 8000
    volumes:
      - ./static_html/src:/app

volumes:
  dc_managed_db_volume: